version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses_test
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  expenses:
    build: .
    container_name: expenses-test
    working_dir: /app
    env_file: ./.env.test
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
    command: sh -c "yarn test"
