services:
  expenses:
    image: node:18-alpine
    command: sh -c "yarn install && yarn test"
    container_name: expenses-test
    depends_on:
      - postgres
      - redis
    env_file: ./.env.test
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
    working_dir: /app

  postgres:
    container_name: express-postgres-test
    environment:
      POSTGRES_DB: expenses-test
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  redis:
    command: redis-server --save 20 1 --loglevel warning
    container_name: expenses-redis-test
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./.redis:/data

version: "3.9"
