version: "3.9"

services:
  redis:
    image: redis:7.0-alpine
    container_name: expenses-redis-test
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.redis:/data

  postgres:
    image: postgres:14-alpine
    container_name: express-postgres-test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses-test
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  expenses:
    build: .
    container_name: expenses-test
    working_dir: /app
    env_file: ./.env.test
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
      - redis
    command: sh -c "yarn install && yarn test"
